# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec_browse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecules',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
